-- ==========================================
-- SVKM CAMPUS FOOD ORDERING SYSTEM DATABASE
-- RDBMS SQL SCHEMA & DATA DUMP
-- Compatible with: MySQL / PostgreSQL / SQLite
-- ==========================================

DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS coupons;
DROP TABLE IF EXISTS food_items;
DROP TABLE IF EXISTS users;

-- 1. USERS TABLE
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) DEFAULT 'student',
    canteen VARCHAR(50) DEFAULT 'ground',
    food_pref VARCHAR(20) DEFAULT 'normal',
    svkm_coins INT DEFAULT 0,
    loyalty_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, name, email, password, role, canteen, food_pref, svkm_coins, loyalty_count) VALUES (1, 'SVKM Admin', 'admin@svkm.edu', 'admin', 'admin', 'all', 'all', 100, 0);
INSERT INTO users (id, name, email, password, role, canteen, food_pref, svkm_coins, loyalty_count) VALUES (2, 'Aarav Shah', 'student@svkm.edu', 'student', 'student', 'ground', 'jain', 71, 19);
INSERT INTO users (id, name, email, password, role, canteen, food_pref, svkm_coins, loyalty_count) VALUES (3, 'Prof. Kothari', 'teacher@svkm.edu', 'teacher', 'teacher', '6th_floor', 'jain', 25, 4);

-- 2. FOOD ITEMS (MENU) TABLE
CREATE TABLE food_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    canteen_ids VARCHAR(100),
    is_jain BOOLEAN DEFAULT 0,
    state_cuisine VARCHAR(50),
    rating DECIMAL(2,1) DEFAULT 4.5,
    reviews_count INT DEFAULT 0,
    prep_time INT DEFAULT 10,
    stock_status VARCHAR(20) DEFAULT 'in_stock',
    image_url VARCHAR(255)
);

INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (1, 'Classic Amul Butter Pav Bhaji', 'Mashed spiced vegetables cooked on a tawa with copious Amul butter. Served with 2 soft buttered pavs, diced red onion, and lemon wedge.', 130, 'Street Food & Chaat', 'ground', 0, 'Maharashtra', 4.9, 612, 8, 'in_stock', '/images/food/pav-bhaji.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (2, 'Jain Special Butter Pav Bhaji', '100% Jain certified recipe made from boiled raw banana, tomatoes, green peas, and capsicum. Cooked in Amul butter with no root vegetables.', 140, 'Street Food & Chaat', 'ground,6th_floor', 1, 'Maharashtra', 4.8, 420, 8, 'in_stock', '/images/food/pav-bhaji.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (3, 'Mumbai Jumbo Vada Pav', 'Golden crispy spiced batata vada nestled inside fresh pav bun with fiery red garlic lasun chutney and spicy green mint sauce.', 35, 'Street Food & Chaat', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.9, 850, 3, 'in_stock', '/images/food/vada-pav.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (4, 'Cheese Schezwan Vada Pav Grill', 'College favorite hot-pressed grilled vada pav loaded with melted mozzarella cheese and spicy wok-tossed Schezwan sauce.', 55, 'Street Food & Chaat', 'ground,8th_floor', 0, 'Maharashtra', 4.8, 530, 5, 'in_stock', '/images/food/vada-pav.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (5, 'Crispy Punjabi Samosa (Plate of 2)', 'Flaky, crisp golden pastry filled with hearty cumin-spiced potatoes and green peas. Served with sweet tamarind and spicy mint chutneys.', 45, 'Street Food & Chaat', 'ground,6th_floor', 0, 'North India', 4.7, 490, 4, 'in_stock', '/images/food/samosa.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (6, 'Kutchi Dabeli (Double Butter & Peanuts)', 'Spicy sweet potato mash inside toasted pav bun, loaded with spiced masala peanuts, sweet pomegranate pearls, and nylon sev.', 45, 'Street Food & Chaat', 'ground,6th_floor', 0, 'Gujarat', 4.7, 360, 4, 'in_stock', '/images/food/dabeli.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (7, 'Kolhapuri Kat Misal Pav (Spicy)', 'Fiery sprouted moth bean curry topped with crunchy farsan mix, fresh onions, coriander, and served with 2 pavs and lemon.', 100, 'Street Food & Chaat', 'ground,8th_floor', 0, 'Maharashtra', 4.8, 390, 6, 'in_stock', '/images/food/misal-pav.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (8, 'Desi Ghee Kanda Poha with Sev', 'Light, fluffy flattened rice tempered with mustard seeds, turmeric, green chillies, curry leaves, and crunchy roasted peanuts.', 50, 'Street Food & Chaat', 'ground,6th_floor', 0, 'Maharashtra', 4.8, 310, 4, 'in_stock', '/images/food/poha.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (9, 'Irani Bun Maska Jam', 'Fresh, warm soft bakery bun generously layered with Amul white butter and sweet mixed fruit strawberry jam.', 40, 'Street Food & Chaat', 'ground,6th_floor,8th_floor', 1, 'Maharashtra', 4.9, 580, 3, 'in_stock', '/images/food/bun-maska.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (10, 'Mumbai Beach Bhel Puri', 'Crisp puffed rice tossed with diced onions, boiled potatoes, tangy tamarind chutney, spicy coriander paste, and crunchy papdi.', 60, 'Street Food & Chaat', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.7, 420, 4, 'in_stock', '/images/food/bhel-puri.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (11, 'Crispy Sev Puri Chaat (6 Pcs)', 'Crispy flat puris laden with diced potatoes, sprouted beans, trio of sweet, tangy and spicy chutneys, and a mountain of yellow nylon sev.', 70, 'Street Food & Chaat', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.9, 670, 5, 'in_stock', '/images/food/sev-puri.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (12, 'Golden Pani Puri (8 Pcs with Pudina Pani)', 'Crisp puffed puris filled with ragda sprouts and drowned in ice-chilled mint coriander spicy water and sweet dates chutney.', 50, 'Street Food & Chaat', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.9, 910, 4, 'in_stock', '/images/food/pani-puri.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (13, 'Chilled Dahi Batata Puri (6 Pcs)', 'Crispy puris stuffed with potato masala, whipped sweetened curd, roasted cumin, tamarind glaze, and sev sprinkles.', 80, 'Street Food & Chaat', 'ground,6th_floor', 0, 'Maharashtra', 4.8, 380, 5, 'in_stock', '/images/food/dahi-puri.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (14, 'Tri-Layer Grilled Vegetable Cheese Sandwich', 'Three slices of buttered bread filled with cucumber, beetroot, tomato, potato masala, and melted cheese with crisp golden grill marks.', 90, 'Street Food & Chaat', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.8, 540, 7, 'in_stock', '/images/food/grilled-sandwich.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (15, 'Cheese Chilli Toast (Open-Faced Grill)', 'Thick crust bread smothered in spiced cheddar and mozzarella cheese, finely diced green chillies, and baked till bubbling golden.', 85, 'Street Food & Chaat', 'ground', 1, 'Maharashtra', 4.7, 290, 6, 'in_stock', '/images/food/cheese-toast.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (16, 'Spiced Paneer Tikka Frankie Roll', 'Soft warm paratha wrap rolled with marinated chargrilled paneer cubes, crunchy onions, and tangy chaat frankie masala.', 95, 'Street Food & Chaat', 'ground,8th_floor', 0, 'Maharashtra', 4.8, 480, 6, 'in_stock', '/images/food/frankie-roll.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (17, 'Surati Locho with Butter & Sev', 'Surat''s famed steamed gram flour delicacy served steaming hot with a generous dollop of Amul butter, spicy green chutney, and crunchy sev.', 90, 'Gujarati Special', 'ground,6th_floor', 1, 'Gujarat', 4.9, 340, 6, 'in_stock', '/images/food/locho.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (18, 'Nylon Khaman Dhokla (Plate of 4)', 'Spongy, juicy, melt-in-mouth steamed savory cakes tempered with mustard seeds, sesame, curry leaves, and fresh green chillies.', 60, 'Gujarati Special', 'ground,6th_floor,8th_floor', 1, 'Gujarat', 4.8, 510, 4, 'in_stock', '/images/food/dhokla.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (19, 'Methi Thepla with Mango Chunda (3 Pcs)', 'Thin, fragrant whole-wheat flatbreads kneaded with fresh fenugreek leaves, curd and aromatic spices. Served with sweet mango chunda.', 80, 'Gujarati Special', 'ground,6th_floor', 1, 'Gujarat', 4.7, 280, 5, 'in_stock', '/images/food/thepla.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (20, 'Crispy Vegetable Handvo with Sesame Tadka', 'Traditional Gujarati baked savory lentil and vegetable cake featuring bottle gourd, tempered with sesame and mustard seeds.', 95, 'Gujarati Special', 'ground,6th_floor', 1, 'Gujarat', 4.6, 190, 7, 'in_stock', '/images/food/handvo.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (21, 'Khandvi Rolls with Mustard & Fresh Coconut', 'Silky, delicate tightly rolled gram flour spirals tempered with mustard seeds and garnished with grated coconut and coriander.', 75, 'Gujarati Special', 'ground,6th_floor', 1, 'Gujarat', 4.8, 230, 4, 'in_stock', '/images/food/khandvi.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (22, 'Sev Tameta Nu Shaak with 3 Phulkas', 'Sweet and tangy tomato curry topped with crisp ratlami sev, served alongside 3 piping hot ghee-brushed phulkas.', 110, 'Gujarati Special', 'ground,6th_floor', 1, 'Gujarat', 4.7, 210, 8, 'in_stock', '/images/food/sev-tameta.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (23, 'Homestyle Gujarati Dal Dhokli Bowl', 'Wholesome sweet, spicy, and tangy toor dal simmering with soft spiced wheat flour dumplings, peanuts, and ghee.', 105, 'Gujarati Special', 'ground,6th_floor', 1, 'Gujarat', 4.8, 260, 8, 'in_stock', '/images/food/dal-dhokli.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (24, 'Crispy Butter Masala Dosa with Sambhar & 2 Chutneys', 'Golden paper-thin fermented rice crepe roasted in Amul butter, filled with spiced potato masala. Served with hot lentil sambhar and chutneys.', 90, 'South Indian', 'ground,6th_floor,8th_floor', 0, 'South Indian', 4.9, 740, 7, 'in_stock', '/images/food/dosa.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (25, 'Jain Butter Dosa (Raw Banana Masala)', 'Crispy fermented crepe filled with Jain-compliant spiced raw banana and turmeric filling, roasted in pure butter.', 95, 'South Indian', 'ground,6th_floor', 1, 'South Indian', 4.7, 310, 7, 'in_stock', '/images/food/dosa.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (26, 'Steamed Button Idli Sambhar Dip (12 Pcs)', 'Pillow-soft mini steamed button idlis soaked in a steaming bowl of aromatic vegetable sambhar with fresh coconut chutney.', 65, 'South Indian', 'ground,6th_floor,8th_floor', 1, 'South Indian', 4.8, 420, 4, 'in_stock', '/images/food/idli.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (27, 'Crispy Medu Vada (2 Pcs) with Sambhar', 'Golden brown, crunchy on the outside, fluffy inside lentil doughnuts spiced with black pepper and cumin. Served with hot sambar.', 70, 'South Indian', 'ground,6th_floor', 0, 'South Indian', 4.8, 360, 5, 'in_stock', '/images/food/medu-vada.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (28, 'Onion Tomato Chilli Uttapam', 'Thick savory fermented pancake topped with caramelized red onions, juicy diced tomatoes, green chillies, and fresh coriander.', 85, 'South Indian', 'ground,6th_floor,8th_floor', 0, 'South Indian', 4.7, 290, 7, 'in_stock', '/images/food/uttapam.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (29, 'Authentic Degree Filter Coffee (Hot Dabarah)', 'Freshly brewed dark roasted chicory-coffee decoction frothed with boiling whole milk, served in traditional stainless steel tumbler.', 30, 'South Indian', 'ground,6th_floor,8th_floor', 1, 'South Indian', 4.9, 820, 3, 'in_stock', '/images/food/filter-coffee.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (30, 'Delhi Chole Bhature (2 Giant Puffed Bhatures)', 'Giant golden puffed bhatures served with dark, aromatic Amritsari chickpea chole, pickled ginger juliennes, and mint chutney.', 140, 'North Indian & Meals', 'ground,8th_floor', 0, 'North India', 4.9, 650, 9, 'in_stock', '/images/food/chole-bhature.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (31, 'Paneer Butter Masala Combo with 2 Butter Naans', 'Succulent cottage cheese cubes simmered in a velvety, rich tomato, butter, and cashew gravy. Served with 2 hot butter naans.', 180, 'North Indian & Meals', 'ground,6th_floor,8th_floor', 0, 'North India', 4.8, 520, 10, 'in_stock', '/images/food/paneer-butter-masala.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (32, 'Jain Shahi Paneer with 3 Phulkas', 'Rich saffron and cardamom-scented white gravy made with melon seeds and cashew cream, cooked with fresh paneer. 100% Jain.', 170, 'North Indian & Meals', 'ground,6th_floor', 1, 'North India', 4.7, 290, 9, 'in_stock', '/images/food/paneer-butter-masala.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (33, 'Dal Makhani Slow-Cooked Over Charcoal', 'Whole black urad lentils and kidney beans slow-simmered overnight with butter, cream, and Kashmiri red chillies.', 150, 'North Indian & Meals', 'ground,8th_floor', 0, 'North India', 4.8, 370, 8, 'in_stock', '/images/food/dal-makhani.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (34, 'Rajma Chawal Deluxe College Bowl', 'North Indian comfort meal: tender Jammu rajma beans cooked in thick tomato gravy served over fragrant steamed basmati rice with pickle.', 120, 'North Indian & Meals', 'ground,6th_floor,8th_floor', 0, 'North India', 4.9, 580, 5, 'in_stock', '/images/food/rajma-chawal.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (35, 'Street Style Veg Hakka Noodles', 'Wok-tossed thin wheat noodles with shredded cabbage, bell peppers, carrots, spring onions, and dark soy garlic sauce.', 110, 'Pan-Asian & Chinese', 'ground,6th_floor,8th_floor', 0, 'Pan-Asian', 4.8, 590, 7, 'in_stock', '/images/food/noodles.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (36, 'Triple Schezwan Fried Rice with Gravy Bowl', 'Spicy Schezwan wok-tossed rice and noodles mixed together, served with a separate bowl of sizzling Manchurian gravy.', 150, 'Pan-Asian & Chinese', 'ground,8th_floor', 0, 'Pan-Asian', 4.9, 480, 8, 'in_stock', '/images/food/fried-rice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (37, 'Crispy Chilli Paneer Dry (8 Pcs)', 'Batter-crisped cottage cheese cubes tossed in spicy chilli garlic sauce with crunchy green capsicum and diced onions.', 140, 'Pan-Asian & Chinese', 'ground,8th_floor', 0, 'Pan-Asian', 4.8, 410, 7, 'in_stock', '/images/food/chilli-paneer.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (38, 'Veg Manchurian Dry Balls (8 Pcs)', 'Crispy fried vegetable dumplings tossed in an aromatic Indo-Chinese sauce flavored with ginger, garlic, and coriander.', 120, 'Pan-Asian & Chinese', 'ground,6th_floor,8th_floor', 0, 'Pan-Asian', 4.7, 360, 7, 'in_stock', '/images/food/manchurian.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (39, 'Golden Fried Spring Rolls with Sweet Chilli Dip (6 Pcs)', 'Crispy golden wrappers filled with finely seasoned julienne vegetables and glass noodles. Served with sweet chilli dip.', 110, 'Pan-Asian & Chinese', 'ground,8th_floor', 0, 'Pan-Asian', 4.7, 290, 6, 'in_stock', '/images/food/spring-rolls.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (40, 'Steamed Vegetable Momos with Fiery Red Sauce (6 Pcs)', 'Thin translucent handmade steamed dumplings packed with finely minced cabbage, carrots, and paneer. Served with fiery red chilli chutney.', 90, 'Pan-Asian & Chinese', 'ground,8th_floor', 0, 'Pan-Asian', 4.9, 670, 6, 'in_stock', '/images/food/momos.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (41, 'Veggie California Sushi Roll (8 Pcs)', 'Premium short-grain sushi rice rolled with crisp cucumber, creamy avocado, carrots, and toasted sesame seeds with soy and wasabi.', 220, 'Pan-Asian & Chinese', '8th_floor', 1, 'Pan-Asian', 4.9, 240, 9, 'in_stock', '/images/food/sushi.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (42, 'Edamame Sea Salt Steamed Pods', 'Tender whole green young soybean pods steamed and seasoned with coarse flaked sea salt. Nutritious and healthy.', 150, 'Pan-Asian & Chinese', '8th_floor', 1, 'Pan-Asian', 4.7, 140, 4, 'in_stock', '/images/food/edamame.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (43, 'Classic Italian Margherita Pizza with Fresh Basil', 'Thin hand-stretched crust baked with San Marzano tomato reduction, melted mozzarella cheese blend, and fresh basil leaves.', 180, 'Fast Food, Pizza & Pasta', 'ground,8th_floor', 1, 'Italian', 4.8, 460, 11, 'in_stock', '/images/food/margherita-pizza.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (44, 'Farmhouse Veggie Exotica Pizza (Loaded)', 'Loaded pizza baked with bell peppers, sweet corn, sliced button mushrooms, black olives, onions, and rich stringy mozzarella.', 220, 'Fast Food, Pizza & Pasta', 'ground,8th_floor', 0, 'Italian', 4.8, 390, 12, 'in_stock', '/images/food/farmhouse-pizza.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (45, 'Penne Arrabiata Spicy Red Tomato Sauce', 'Al dente penne pasta tossed in fiery Italian tomato sauce infused with garlic, chilli flakes, oregano, and grated parmesan.', 150, 'Fast Food, Pizza & Pasta', 'ground,8th_floor', 0, 'Italian', 4.7, 270, 10, 'in_stock', '/images/food/arrabiata-pasta.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (46, 'Creamy White Alfredo Penne Pasta', 'Penne pasta enveloped in a rich, velvety white cream sauce made with butter, parmesan, sautéed mushrooms, and cracked black pepper.', 165, 'Fast Food, Pizza & Pasta', 'ground,8th_floor', 1, 'Italian', 4.8, 310, 10, 'in_stock', '/images/food/alfredo-pasta.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (47, 'Crispy Peri Peri French Fries', 'Crispy, golden skin-on potato fries tossed in fiery African peri-peri spice dust. Served hot with cheesy dip.', 80, 'Fast Food, Pizza & Pasta', 'ground,6th_floor,8th_floor', 0, 'Continental', 4.9, 610, 5, 'in_stock', '/images/food/french-fries.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (48, 'Cheese Loaded Nachos with Jalapeños & Salsa', 'Crisp stone-ground corn tortilla chips drenched in warm melted cheddar cheese sauce, pickled jalapeños, and fresh salsa.', 110, 'Fast Food, Pizza & Pasta', 'ground,8th_floor', 1, 'Mexican', 4.7, 340, 5, 'in_stock', '/images/food/nachos.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (49, 'Cutting Adrak Elaichi Chai (Kulhad)', 'Steaming aromatic milk tea brewed with crushed ginger roots, fragrant green cardamom, and Assam tea leaves in earthen kulhad.', 20, 'Beverages & Chai', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.9, 980, 3, 'in_stock', '/images/food/chai.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (50, 'Iced Cold Coffee with Vanilla Ice Cream', 'Chilled blended coffee made with rich milk and chocolate drizzle, topped with a luscious scoop of creamy vanilla ice cream.', 70, 'Beverages & Chai', 'ground,6th_floor,8th_floor', 1, 'Continental', 4.9, 810, 4, 'in_stock', '/images/food/cold-coffee.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (51, 'Thick Chocolate Oreo Mudshake', 'Decadent thick milkshake blended with crunchy Oreo cookies, chocolate ganache, and topped with cookie crumble.', 90, 'Beverages & Chai', 'ground,8th_floor', 1, 'Continental', 4.8, 460, 4, 'in_stock', '/images/food/oreo-shake.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (52, 'Spiced Masala Chaas (Roasted Cumin & Mint Buttermilk)', 'Refreshing, cooling light spiced yogurt drink tempered with roasted cumin powder, black salt, and fresh garden mint.', 25, 'Beverages & Chai', 'ground,6th_floor,8th_floor', 1, 'Gujarat', 4.8, 530, 2, 'in_stock', '/images/food/masala-chaas.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (53, 'Patiala Sweet Lassi with Malai & Pistachios', 'Creamy, chilled, thick churned yogurt drink served in a tall glass, topped with a thick layer of clotted malai and crushed nuts.', 60, 'Beverages & Chai', 'ground,6th_floor', 1, 'North India', 4.9, 390, 4, 'in_stock', '/images/food/sweet-lassi.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (54, 'Royal Kesar Badam Thandai Shake', 'Traditional cooling drink enriched with saffron threads, crushed almonds, fennel seeds, and rose water.', 80, 'Beverages & Chai', 'ground,6th_floor', 1, 'North India', 4.8, 220, 4, 'in_stock', '/images/food/thandai.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (55, 'Fresh Crushed Sugarcane Juice with Ginger & Lemon', 'Hygienically cold-pressed natural sugarcane juice with fresh lemon and ginger extract over crushed ice. Naturally energizing.', 40, 'Fresh Juices & Coolers', 'ground,6th_floor', 0, 'Maharashtra', 4.9, 730, 3, 'in_stock', '/images/food/sugarcane-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (56, 'Fresh Watermelon Mint Cooler', '100% pure watermelon juice freshly squeezed to order with fresh crushed garden mint leaves and black salt. No added sugar.', 60, 'Fresh Juices & Coolers', 'ground,6th_floor,8th_floor', 1, 'Maharashtra', 4.8, 410, 3, 'in_stock', '/images/food/watermelon-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (57, 'Pure Pomegranate (Anar) Fresh Juice', 'Rich ruby red fresh pomegranate juice squeezed fresh without water dilution. Antioxidant powerhouse.', 90, 'Fresh Juices & Coolers', 'ground,6th_floor,8th_floor', 1, 'Maharashtra', 4.9, 320, 4, 'in_stock', '/images/food/pomegranate-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (58, 'Alphonso Mango Thick Shake', 'Rich, velvety summer special shake made with ripe Ratnagiri Alphonso mango pulp and chilled creamy milk.', 95, 'Fresh Juices & Coolers', 'ground,6th_floor,8th_floor', 1, 'Maharashtra', 4.9, 850, 4, 'in_stock', '/images/food/mango-shake.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (59, 'Fresh Mosambi (Sweet Lime) Juice', 'Freshly cold-pressed sweet lime citrus juice with a pinch of black salt. Refreshing and packed with Vitamin C.', 60, 'Fresh Juices & Coolers', 'ground,6th_floor', 1, 'Maharashtra', 4.7, 380, 3, 'in_stock', '/images/food/mosambi-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (60, 'Tropical Pineapple Mint Juice', 'Zesty freshly pressed golden pineapple juice accented with crushed fresh mint sprigs. Tangy and refreshing.', 65, 'Fresh Juices & Coolers', 'ground,6th_floor', 1, 'Maharashtra', 4.8, 240, 3, 'in_stock', '/images/food/pineapple-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (61, 'Green Detox Cleanser Juice (Cucumber, Mint, Spinach)', 'Rejuvenating wellness juice pressed with fresh cucumber, spinach, green apple, lemon, and mint leaves.', 80, 'Fresh Juices & Coolers', 'ground,8th_floor', 1, 'Healthy', 4.6, 170, 4, 'in_stock', '/images/food/detox-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (75, 'Fresh Mahabaleshwar Strawberry Juice', 'Pure cold-pressed ruby red juice from freshly plucked Mahabaleshwar strawberries with a splash of fresh lime and mint sprig. 100% real fruit, no artificial syrup.', 85, 'Fresh Juices & Coolers', 'ground,6th_floor,8th_floor', 1, 'Maharashtra', 4.9, 530, 4, 'in_stock', '/images/food/strawberry-juice.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (62, 'Sizzling Chocolate Brownie with Hot Fudge & Vanilla Ice Cream', 'Warm dark chocolate walnut brownie on cast-iron sizzler plate, crowned with vanilla ice cream and bubbling hot chocolate sauce.', 130, 'Desserts & Ice Cream', 'ground,8th_floor', 1, 'Continental', 4.9, 820, 6, 'in_stock', '/images/food/brownie.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (63, 'Death By Chocolate (DBC) Sundae Jar', 'Layered tall mason jar featuring chocolate sponge cake, double scoops of chocolate ice cream, roasted nuts, and chocolate fudge.', 140, 'Desserts & Ice Cream', 'ground,8th_floor', 1, 'Continental', 4.9, 490, 5, 'in_stock', '/images/food/sundae.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (64, 'Nutella Belgian Waffle with Vanilla Dip', 'Freshly baked crisp Belgian waffle with deep pockets smothered in warm Nutella hazelnut spread, dusted with powdered sugar.', 120, 'Desserts & Ice Cream', 'ground,8th_floor', 1, 'Continental', 4.8, 530, 7, 'in_stock', '/images/food/waffle.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (65, 'Warm Gulab Jamun with Rabdi (2 Pcs)', 'Soft, golden brown khoya dumplings soaked in fragrant cardamom rose syrup, served warm over chilled creamy thick rabdi.', 70, 'Desserts & Ice Cream', 'ground,6th_floor', 1, 'North India', 4.9, 410, 3, 'in_stock', '/images/food/gulab-jamun.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (66, 'Kesar Pista Matka Kulfi (Clay Pot)', 'Authentic slow-reduced milk kulfi infused with Kashmiri saffron and slivered pistachios, frozen traditionally in earthen pot.', 65, 'Desserts & Ice Cream', 'ground,6th_floor,8th_floor', 1, 'North India', 4.8, 360, 2, 'in_stock', '/images/food/kulfi.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (67, 'Delicate Kesar Rasmalai (2 Pcs)', 'Spongy, pillowy cottage cheese discs steeped in chilled sweetened saffron-cardamom milk, garnished with slivered almonds.', 80, 'Desserts & Ice Cream', 'ground,6th_floor', 1, 'North India', 4.9, 420, 2, 'in_stock', '/images/food/rasmalai.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (68, 'Tender Coconut Ice Cream Scoop', 'Natural''s style artisanal ice cream churned with pure milk, cream, and tender malai bits from fresh green coconuts.', 65, 'Desserts & Ice Cream', 'ground,6th_floor,8th_floor', 1, 'Maharashtra', 4.9, 510, 2, 'in_stock', '/images/food/coconut-ice-cream.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (69, 'Warm Molten Choco Lava Cake', 'Freshly baked individual chocolate cake with a warm, gooey molten chocolate ganache center that flows out at the first spoon.', 85, 'Desserts & Ice Cream', 'ground,8th_floor', 1, 'Continental', 4.8, 370, 5, 'in_stock', '/images/food/choco-lava.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (70, 'Doritos Nacho Cheese with Jalapeño Dip', 'Crunchy triangular corn tortilla chips with intense nacho cheese flavor. Served with sealed cheese jalapeño dipping tub.', 50, 'Grab & Go Snacks', 'ground,6th_floor,8th_floor', 1, 'Packaged', 4.7, 320, 1, 'in_stock', '/images/food/doritos.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (71, 'Balaji Wafers Cream & Onion Pack', 'Crispy ridged golden potato wafers seasoned with tangy sour cream and herb onion seasoning.', 25, 'Grab & Go Snacks', 'ground,6th_floor,8th_floor', 0, 'Packaged', 4.6, 410, 1, 'in_stock', '/images/food/potato-chips.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (72, 'Cadbury Dairy Milk Silk Roasted Almond Bar', 'Rich, smooth melt-in-mouth milk chocolate packed with whole crunchy roasted almonds (58g pack).', 90, 'Grab & Go Snacks', 'ground,6th_floor,8th_floor', 1, 'Packaged', 4.9, 670, 1, 'in_stock', '/images/food/chocolate-bar.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (73, 'Ferrero Rocher Hazelnut Pralines (Pack of 3)', 'Crispy wafer balls filled with whole crunchy hazelnut and rich chocolate cream, coated in milk chocolate and chopped hazelnuts.', 120, 'Grab & Go Snacks', 'ground,8th_floor', 1, 'Packaged', 4.9, 310, 1, 'in_stock', '/images/food/ferrero.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (74, 'RiteBite Max Protein Choco Slim Bar (20g Protein)', 'Healthy fitness energy bar packed with 20g whey & soy protein, 21 essential vitamins, and zero added sugar.', 110, 'Grab & Go Snacks', 'ground,8th_floor', 1, 'Fitness', 4.7, 280, 1, 'in_stock', '/images/food/protein-bar.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (76, 'Classic Pav Bhaji + Mango Lassi Combo', 'Signature Amul Butter Pav Bhaji served with 2 extra butter pavs and a tall chilled glass of golden Mango Lassi. (Save ?35!)', 185, 'Combos & Value Meals', 'ground,6th_floor,8th_floor', 0, 'Maharashtra', 4.9, 320, 10, 'in_stock', '/images/food/pav-bhaji.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (77, 'Jain Deluxe Thali + Roasted Jeera Chaas Combo', 'Authentic 100% Jain Thali with 3 Rotlis, Paneer Shak, Dal, Rice, Salad and chilled roasted jeera buttermilk chaas.', 199, 'Combos & Value Meals', 'ground,6th_floor,8th_floor', 1, 'Gujarat', 4.8, 245, 12, 'in_stock', '/images/food/gujarati-thali.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (78, 'Delhi Chole Bhature + Sweet Punjabi Lassi Combo', '2 crispy golden Bhature with rich Amritsari Pindi Chole, onion-chilli relish, and thick sweet creamy Malai Lassi.', 175, 'Combos & Value Meals', 'ground,6th_floor,8th_floor', 0, 'North Indian', 4.9, 410, 10, 'in_stock', '/images/food/chole-bhature.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (79, 'South Indian Tiffin Combo (Idli + Vada + Filter Coffee)', '2 fluffy steamed Idlis, 1 crispy Medu Vada with hot Sambhar, fresh coconut chutney & authentic tumbler Filter Coffee.', 135, 'Combos & Value Meals', 'ground,6th_floor,8th_floor', 1, 'South Indian', 4.8, 190, 8, 'in_stock', '/images/food/idli.jpg');
INSERT INTO food_items (id, name, description, price, category, canteen_ids, is_jain, state_cuisine, rating, reviews_count, prep_time, stock_status, image_url) VALUES (80, 'Campus Burger + Peri Peri Fries + Cold Coffee Meal', 'Crispy Veg Patty Burger loaded with cheese, hot Peri Peri French Fries, and frothy chilled Nescafe Cold Coffee.', 195, 'Combos & Value Meals', 'ground,6th_floor,8th_floor', 0, 'Fast Food', 4.9, 530, 10, 'in_stock', '/images/food/burger.jpg');

-- 3. COUPONS TABLE
CREATE TABLE coupons (
    id INT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(30) UNIQUE NOT NULL,
    description VARCHAR(255),
    discount_percent INT DEFAULT 0,
    discount_flat DECIMAL(10,2) DEFAULT 0,
    max_discount DECIMAL(10,2) DEFAULT 0,
    min_order DECIMAL(10,2) DEFAULT 0,
    type VARCHAR(30) DEFAULT 'regular',
    is_active BOOLEAN DEFAULT 1,
    redemption_count INT DEFAULT 0
);

INSERT INTO coupons (id, code, description, discount_percent, discount_flat, max_discount, min_order, type, is_active, redemption_count) VALUES (1, 'HAPPYHOUR15', '15% OFF during campus off-peak hours (9:00 - 11:30 AM & 3:00 - 5:00 PM)', 15, 0, 100, 100, 'time_restricted', 1, 39);
INSERT INTO coupons (id, code, description, discount_percent, discount_flat, max_discount, min_order, type, is_active, redemption_count) VALUES (2, 'GROUP50', 'Flat ?50 OFF on orders of ?500+ for study groups & teams', 0, 50, 0, 500, 'group', 1, 20);
INSERT INTO coupons (id, code, description, discount_percent, discount_flat, max_discount, min_order, type, is_active, redemption_count) VALUES (3, 'FIRSTBITE', 'Flat ?20 OFF on your first cafeteria order at SVKM', 0, 20, 0, 60, 'first_order', 1, 54);
INSERT INTO coupons (id, code, description, discount_percent, discount_flat, max_discount, min_order, type, is_active, redemption_count) VALUES (4, 'SVKM50', '50% OFF up to ?100 on Jain & Gujarati delights', 50, 0, 100, 150, 'regular', 1, 42);
INSERT INTO coupons (id, code, description, discount_percent, discount_flat, max_discount, min_order, type, is_active, redemption_count) VALUES (1789026328372, 'SVKM-FREEBIE-839', '🎉 5th Order Reward! Flat ₹80 OFF on your next order!', 0, 80, 0, 100, 'regular', 1, 0);

-- 4. ORDERS TABLE
CREATE TABLE orders (
    id BIGINT PRIMARY KEY,
    order_code VARCHAR(20) UNIQUE NOT NULL,
    user_id INT,
    user_name VARCHAR(100),
    canteen_id VARCHAR(50),
    canteen_name VARCHAR(100),
    status VARCHAR(30) DEFAULT 'Placed',
    subtotal DECIMAL(10,2),
    discount DECIMAL(10,2) DEFAULT 0,
    total DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(50),
    payment_status VARCHAR(20) DEFAULT 'PAID',
    fulfillment_type VARCHAR(30) DEFAULT 'pickup',
    delivery_location VARCHAR(100),
    pickup_otp VARCHAR(10),
    coins_earned INT DEFAULT 0,
    coins_redeemed INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789034830568, 'SVKM-6803', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Placed', 50, 0, 50, 'Razorpay', 'PAID', 'pickup', 'Self-Pickup at Counter', '1774', 2, 0, '2026-09-10 10:07:10');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789034774789, 'SVKM-4375', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Placed', 70, 0, 70, 'Razorpay', 'PAID', 'pickup', 'Self-Pickup at Counter', '5092', 3, 0, '2026-09-10 10:06:14');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789034328264, 'SVKM-2344', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Preparing', 170, 25.5, 144.5, 'Razorpay', 'PAID', 'pickup', 'Self-Pickup at Counter', '8347', 7, 0, '2026-09-10 09:58:48');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789027039412, 'SVKM-8158', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Preparing', 50, 0, 50, 'Razorpay', 'PAID', 'pickup', 'Self-Pickup at Counter', '1562', 2, 0, '2026-09-10 07:57:19');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789026328371, 'SVKM-2484', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Preparing', 90, 0, 90, 'Razorpay', 'PAID', 'pickup', 'Self-Pickup at Counter', '5930', 4, 0, '2026-09-10 07:45:28');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789026195219, 'SVKM-8085', 2, 'Aarav Shah', '8th_floor', '8th Floor Sky Lounge', 'Completed', 140, 0, 140, 'Razorpay UPI', 'PAID', 'pickup', 'Self-Pickup at Counter', '4487', 7, 0, '2026-09-10 07:43:15');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789023260945, 'SVKM-9966', 2, 'Aarav Shah', 'ground', 'Ground Floor Canteen', 'Completed', 370, 50, 320, 'Razorpay UPI', 'PAID', 'pickup', 'Self-Pickup at Counter', '4449', 16, 10, '2026-09-10 06:54:20');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789021894765, 'SVKM-9537', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Completed', 220, 0, 220, 'Razorpay', 'PAID', 'pickup', 'Self-Pickup at Counter', '4903', 0, 0, '2026-09-10 06:31:34');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789020605780, 'SVKM-7919', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Completed', 185, 92.5, 92.5, 'Google Pay', 'PAID', 'pickup', 'Self-Pickup at Counter', '9537', 0, 0, '2026-09-10 06:10:05');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789018455407, 'SVKM-9558', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Completed', 135, 0, 135, 'Counter QR Scanner', 'PAID', 'pickup', 'Self-Pickup at Counter', '1534', 0, 0, '2026-09-10 05:34:15');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789016347264, 'SVKM-1153', 3, 'Prof. R. Mehta (Faculty)', '6th_floor', '6th Floor - Faculty & Student Hub', 'Ready', 110, 0, 110, 'Razorpay UPI', 'PAID', 'delivery', 'Cabin 604, Computer Engineering Dept (Ext: 4210)', '9124', 0, 0, '2026-09-10 04:59:07');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789016347257, 'SVKM-8466', 2, 'Aarav Shah (Student)', 'ground', 'Ground Floor - Main Campus Plaza', 'Completed', 90, 0, 90, 'Razorpay UPI', 'PAID', 'pickup', 'Self-Pickup at Counter', '4819', 0, 0, '2026-09-10 04:59:07');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789016313420, 'SVKM-2170', 3, 'Prof. R. Mehta (Faculty)', '6th_floor', '6th Floor - Faculty & Student Hub', 'Ready', 110, 0, 110, 'Razorpay UPI', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 04:58:33');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789016313413, 'SVKM-6140', 2, 'Aarav Shah (Student)', 'ground', 'Ground Floor - Main Campus Plaza', 'Completed', 90, 0, 90, 'Razorpay UPI', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 04:58:33');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789015128023, 'SVKM-5454', 2, 'Aarav Shah', '6th_floor', '6th Floor - Faculty & Student Hub', 'Completed', 30, 0, 30, 'Counter QR Scanner', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 04:38:48');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789015062969, 'SVKM-6829', 2, 'Aarav Shah', '6th_floor', '6th Floor - Faculty & Student Hub', 'Placed', 20, 0, 20, 'Counter QR Scanner', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 04:37:42');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (1789014035046, 'SVKM-5102', 2, 'Aarav Shah', 'ground', 'Ground Floor - Main Campus Plaza', 'Completed', 300, 50, 250, 'Razorpay UPI (Google Pay)', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 04:20:35');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (101, 'SVKM-9021', 2, 'Aarav Shah', 'ground', 'Ground Floor Canteen', 'Completed', 240, 0, 240, 'Razorpay UPI (Fast)', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 04:00:43');
INSERT INTO orders (id, order_code, user_id, user_name, canteen_id, canteen_name, status, subtotal, discount, total, payment_method, payment_status, fulfillment_type, delivery_location, pickup_otp, coins_earned, coins_redeemed, created_at) VALUES (102, 'SVKM-8834', 3, 'Prof. Kothari', '6th_floor', '6th Floor Faculty Canteen', 'Completed', 170, 20, 150, 'Counter UPI QR', 'PAID', 'pickup', 'Self-Pickup', '0000', 0, 0, '2026-09-10 03:40:43');
